# image: node:latest

# before_script:
#   - apt-get update -qy
#   - apt-get install -y ruby-dev
#   - gem install dpl

# stages:
#   - production

# production:
#   stage: production
#   image: ruby:latest
#   script:
#     - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
#   only:
#     - production

default:
  image: node:latest

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  image: node:18-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build

# unit-tests:
#   image: node:latest
#   stage: test
#   only:
#     - master
#   before_script:
#     - npm install
#   script:
#     - npm run test:ci
#   coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
#   artifacts:
#     paths:
#       - coverage/
#     when: always
#     reports:
#       junit:
#         - junit.xml

e2e_tests:
  stage: test
  image: cypress/base:latest
  script:
    - npm ci
    - npm install -g serve
    - npm install -g wait-on
    - serve -s build &
    - wait-on http://localhost:3000
    - npm run cypress-run

deploy_production:
  stage: deploy
  only:
    - production
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
